### ISSUE TITLE
MultiversalPageProps as generic parameter

### ISSUE THREAD

**Issue by crisfcodes** [UnlyEd/next-right-now#104]
https://github.com/UnlyEd/next-right-now/blob/94ae2f9c1aa98eadeab33fd6eef79f3e84dffde3/src/types/nextjs/MultiversalAppBootstrapProps.ts#L11

I find this pattern `type MultiversalAppBootstrapProps<PP extends MultiversalPageProps = MultiversalPageProps>` in some generic types but i dont whats mean... if PP extends MultiversalPageProps asign the value passes as MultiversalPagePros as default value?? Thanks

**Comment by Vadorequest** [comment]
Because `extends` doesn't meant `equals to`.

If you do:
`export type MultiversalAppBootstrapProps<PP>`
Then, you'll have to specify `PP` in every use, which is rather redundant.

Doing 
`type MultiversalAppBootstrapProps<PP extends MultiversalPageProps = MultiversalPageProps>` 
means that `PP` extends `MultiversalPageProps` and also that it equals `MultiversalPageProps` by default, which means you don't have to specify `PP` value every time, as it makes it optional 
(e.g: `type X extends MultiversalAppBootstrapProps` will work). 

Only when you specify `PP` the compiler will check that your parameter actually matches the expected type. 
(e.g: `type X = MultiversalAppBootstrapProps<string>` will fail)

It's basically a way to write a default (and optional) value, to avoid writing the value at every use.

**Comment by Vadorequest** [comment]
@cristian05 Closing, let me know if it doesn't answer your question.
