### ISSUE TITLE
'NODE_ENV' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by binary64** [UnlyEd/next-right-now#110]
When running `yarn build` on Windows on the v2-mst-aptd-gcms-lcz-sty branch I get 

```
'NODE_ENV' is not recognized as an internal or external command
```

**Comment by Vadorequest** [comment]
Do you know about Cygwin or Babun? 

Babun is another alternative. https://babun.github.io/ It's not maintained but still works perfectly.

That's what I use to emulate a UNIX/POSIX env on my windows.


There is also Cygwin (Babun uses Cygwin)
https://cygwin.com/install.html

If you don't want to use either, know that the issue you're encountering can be fixed rather easily using:
- Git bash - When you install git on windows, it installs git bash, which you can use instead of the windows terminal

The issue you're encountering is because env vars work differently on widnows and unix, maybe running `cross-env next dev --port 8888` would work, I haven't tried that yet.

See https://unlyed.github.io/next-right-now/faq.html#can-i-use-nrn-on-windows

**Comment by Vadorequest** [comment]
@binary64 Did you sort it out?

**Comment by binary64** [comment]
Babun says their project is discontinued. So I think the best option remains is cross-env or cross-env-shell on npm.

**Comment by Vadorequest** [comment]
Yes, it is. But still works perfectly. That's what I use.

Did you sort it out using cross-env anyhow?
