### ISSUE TITLE
Why next-with-apollo?

### ISSUE THREAD

**Issue by samuelcastro** [UnlyEd/next-right-now#146]
Wondering whether or not we should keep [next-with-apollo](https://github.com/lfades/next-with-apollo) considering that we could easily integrate graphql without it: https://github.com/vercel/next.js/blob/canary/examples/with-apollo/lib/apolloClient.js

`next-with-apollo` has a lot of dead code that are meant to be used with `getInitialProps` and `getDataFromTree` which has known [performance issues](https://github.com/vercel/next.js/discussions/10946#discussioncomment-3335).

What's your thoughts?

**Comment by Vadorequest** [comment]
I _theoretically_ agree on this, but I don't have time to perform such a change, and it's not a priority to me. I understand the benefits, but as I am personally running mostly using SSG mode, it doesn't affect me. People using SSR would still be interested, though.

Feel free to make a PR against https://github.com/UnlyEd/next-right-now/tree/v2-mst-aptd-gcms-lcz-sty branch to propose such change. Ideally, I'd love to grant you access to the repo so that you can benefit from CI/CD, but I don't know how that's supposed to work. It's something I really wish to improve [(better OS collaboration)](https://github.com/UnlyEd/next-right-now/discussions/57) but I haven't had time to focus on it, I'd love some suggestions. I was also thinking asking GitHub support about that.

**Comment by samuelcastro** [comment]
Ok, I'll find some time to work on it.

**Comment by Vadorequest** [comment]
I'm tempted to close this due to https://github.com/UnlyEd/next-right-now/issues/211

I feel like there is very little chance for this to be implemented.

**Comment by samuelcastro** [comment]
😞

**Comment by samuelcastro** [comment]
I'd like to keep this and implement it myself if you don't have time. I feel that we should keep GraphQL.

**Comment by Vadorequest** [comment]
@samuelcastro Being the main maintainer of NRN at this time, and building it using my own experience and opinions, I'm not comfortable introducing big changes when I haven't experienced them first-hand in a real production usage. That's how I built NRN so far and it works great, I don't simply decide to add some cool tech, but I experience first with it in our company, and then decide whether/how it should be integrated back to NRN.

I failed to articulate this before, I recently became aware of it, I wasn't really aware of my own train of thoughts, and that's why I'm not comfortable doing this without prior experience.

I'm fine if the experience comes from the community, but I'm not inclined to act as an expert about something if I'm not one.

So, if you wish to experiment with it and implement it into NRN, go for it! But since I won't work with GraphQL for a while I'll definitely not do it myself. I'll review PRs though, and test things thoroughly. :)

**Comment by samuelcastro** [comment]
Ok I understand, I'll work on it.

**Comment by Vadorequest** [comment]
FYI just saw https://github.com/vercel/next.js/discussions/9542#discussioncomment-324734

Updated with-apollo examples:
- https://github.com/vercel/next.js/tree/canary/examples/with-apollo
- https://github.com/borisowsky/next-advanced-apollo-starter

Haven't looked any deeper.

**Comment by samuelcastro** [comment]
Yeah, `next-with-apollo` is totally unnecessary now. I'm going to work on this migration soon. Also I hope to upgrade Apollo.

**Comment by samuelcastro** [comment]
@Vadorequest https://github.com/UnlyEd/next-right-now/pull/291

**Comment by Vadorequest** [comment]
Done in #294, thanks to @samuelcastro
