### ISSUE TITLE
CSSType

### ISSUE THREAD

**Issue by samuelcastro** [UnlyEd/next-right-now#168]
I recommend the usage of [csstype](https://www.npmjs.com/package/csstype) for `style` typing instead of:

```
export type CSSStyles = GenericObject<string | number>;
```

I provides accurate types.

**Comment by Vadorequest** [comment]
It does seem to provide accurate types, but I don't see it as a benefit really.

I couldn't check how much overhead weight it brings onto the project because https://bundlephobia.com/result?p=csstype didn't successfully analyse the package for some reason.

But, the `CSSStyles` is meant to be simple and allow everything, there isn't really a point here about what styles go there. I mean, the current implementation feels enough to me, adding an extra library just because we use `CSSStyles` like 5 times in the project feels like "too much" to be honest. Nothing stops you from doing it, but I'm not confident it'd be a great addition to the project.

Feel free to prove me otherwise, though :wink:

https://github.com/frenic/csstype/issues/112

**Comment by samuelcastro** [comment]
Fair point, I'm using only for typing purposes, I'm getting a few type issues with `CSSStyles`.

**Comment by Vadorequest** [comment]
Could you elaborate a bit on the issues you faced with `CSSStyles`? I might need some improvements then. Maybe `GenericObject<string | number>` is too restrictive? I hadn't considered some advanced CSS use cases

**Comment by Vadorequest** [comment]
Following the comment https://github.com/frenic/csstype/issues/112#issuecomment-693109078, I now see the interest of using such library, and it would indeed prove itself beneficial.

A PR is welcome! 😉

**Comment by samuelcastro** [comment]
Ok great, I'll work on it.

**Comment by Vadorequest** [comment]
Similar to this (better TS types): https://github.com/sindresorhus/type-fest

**Comment by samuelcastro** [comment]
Super helpful indeed!

Btw, I'm planning on working on this tonight.

**Comment by samuelcastro** [comment]
This issue was addressed here: https://github.com/UnlyEd/next-right-now/pull/172
