### ISSUE TITLE
::set-env deprecated | Github Actions

### ISSUE THREAD

**Issue by samuelcastro** [UnlyEd/next-right-now#174]
We need to upgrade `::set-env`.

Article:
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Security issue explained:
https://github.com/actions/toolkit/security/advisories/GHSA-mfwh-5m23-j46w

New way:
https://github.com/actions/toolkit/blob/main/docs/commands.md#environment-files

**Comment by Vadorequest** [comment]
@Demmonius Could you take a look at this?

**Comment by ljosberinn** [comment]
fyi, since I took some heavy inspiration from that build step, I looked into it and this line

https://github.com/UnlyEd/next-right-now/blob/v2-mst-aptd-at-lcz-sty/.github/workflows/deploy-zeit-production.yml#L111

```sh
          echo "::set-env name=ZEIT_DEPLOYMENT_URL::https://$ZEIT_DEPLOYMENT"
```

can be safely replcaed with
```sh
          echo "VERCEL_DEPLOYMENT_URL=https://$VERCEL_DEPLOYMENT" >> $GITHUB_ENV
```

and that's it :)

(applies to the other `::set-env` too obviously)

**Comment by Vadorequest** [comment]
Thanks for the feedback on this @ljosberinn! Looks like a trivial change and should be done once https://github.com/UnlyEd/next-right-now/pull/147 has landed (or, within it, doesn't really matter).

**Comment by Vadorequest** [comment]
Fixed by https://github.com/UnlyEd/next-right-now/pull/147
