### ISSUE TITLE
Sometimes, E2E tests fail because they're testing the Vercel domain instead of the deployment domain

### ISSUE THREAD

**Issue by Vadorequest** [UnlyEd/next-right-now#184]
It happens from time to time that Vercel didn't update the DNS of the newly deployed domain name, and Cypress runs too early and gets redirected to the deployment page, which is protected against unauthenticated users and gets redirected to the homepage.

The deployment page automatically redirects to the deployment domain once the domain has been published, but the login page doesn't.

Therefore, Cypress stays on that login page and perform the tests against the wrong domain, by testing Vercel auth page instead of the deployment.
Using the Cypress `attempts` feature doesn't solve the problem, because Cypress stays on the login page.

I'm not sure what can be done here, maybe cypress should keep redirecting to the deployment url until it works?  

---

### Resources:
- https://glebbahmutov.com/blog/develop-preview-test/

![image](https://user-images.githubusercontent.com/3807458/96439854-65fbbd80-1207-11eb-8020-93a6d6817d95.png)

**Comment by Vadorequest** [comment]
Answer from Vercel support:

![image](https://user-images.githubusercontent.com/3807458/97031581-d0db2a80-1560-11eb-8e4d-42dab157e0dd.png)

Example:
See https://github.com/filipedeschamps/BrasilAPI/blob/master/.github/workflows/e2e-tests.yml

@Demmonius Do you understand what needs to be done? I'm not sure I 100% understand the example

**Comment by Demmonius** [comment]
HI,
I think they advise us to create a github action which block the workflow until the domain is fully created. But is it not possible to do that in Cypress ? By making a "pre" test, waiting for a logo or something on the page ?

We cannot apply the example of `BrasilAPI` because they use the built-in vercel app with Github actions, not a custom system like us. Indeed, the app update the status of the deployment so they know when a deployment is complete.

If you think that it's not possible to perform the "pre tests" with Cypress, we should have a look at the API and use a simple script which call the API and wait for the deployment to be done? I'm sure you are looking forward to do **bash** again :D

**Comment by Vadorequest** [comment]
Maybe a simpler alternative would be to wait for like 10-30sec before starting the E2E action?

I don't think "pre-tests" with Cypress will help here, because they'll get redirected to the wrong domain and get stuck, it won't help IMHO.

The cleanest way to do it would indeed to wait for the deployment to be ready using the Vercel API.
Could that be a separated/reusable action?

https://github.com/marketplace?query=vercel

https://github.com/marketplace/actions/wait-for-vercel seems to be exactly what we're looking for.

**Comment by Demmonius** [comment]
The last link looks perfect, because that's also a way to retrieve the deployment URL so it actually skips a step ;)

**Comment by Vadorequest** [comment]
Solved on both v2 preset branches.

@Demmonius Although, sometimes e2e still crash 😕 But I expect it to happen less often, and I don't see what more we can do about it.
