### ISSUE TITLE
Amplitude setup steps

### ISSUE THREAD

**Issue by sovattha** [UnlyEd/next-right-now#202]
Regarding the setup of Amplitude, I think there are missing steps in the documentation.

I followed every step described here: https://unlyed.github.io/next-right-now/guides/analytics/setup-amplitude and https://unlyed.github.io/next-right-now/guides/analytics/use-amplitude

but I did not have any data in my Amplitude dashboard. I got in touch with their support to understand what is happening.

Apparently, they only received authentication requests to Amplitude, but then no other call is being done. Nothing is tracked.

Is there anything to do to be able to track visitor clicks, page loading, etc.?

**Comment by Vadorequest** [comment]
@sovattha Use https://chrome.google.com/webstore/detail/amplitude-instrumentation/acehfjhnmhbmgkedjmjlobpgdicnhkbp to debug calls to amplitude from the browser.

The doc is wrong about the `NEXT_PUBLIC_AMPLITUDE_API_KEY`, it should be in `.env` file, not `.env.build` (that was the old way, hasn't been updated). **Note that this only works for local testing.**

Staging/production need a Vercel secret to be defined. See https://unlyed.github.io/next-right-now/guides/analytics/setup-amplitude step 9.

**Comment by Vadorequest** [comment]
Just configuring the proper key will automatically make Amplitude track lots of things (page views, etc.), so it's mostly a misconfiguration issue.

**Comment by sovattha** [comment]
Thanks for the quick reply @Vadorequest. But I think I am missing something here...

[The doc](https://unlyed.github.io/next-right-now/guides/analytics/setup-amplitude) does not make mention of a `NEXT_PUBLIC_AMPLITUDE_API_KEY` variable but only of `AMPLITUDE_API_KEY`.
Nevermind, I tried to setup a property `AMPLITUDE_API_KEY` in a new **.env** file so that it is used at runtime and not only during the build process.

The app is deployed in both staging and production. It has the environment variable `AMPLITUDE_API_KEY` defined at the build process so that it is read successfully at runtime.
In **staging**, the variable `amplitudeInstance` is exposed on the window object and I can tell that `amplitudeInstance._isInitialized` is true.
In **production**, as expected the variable is not visible.

It's really like the Amplitude instance is connected correctly BUT does not send events.

From the extension, I can only see $identify events are being caught. No more.

**Comment by Vadorequest** [comment]
It's a bit hard to help because I'm not sure what version of the code you're using.

And obviously, the doc isn't up-to-date with the latest version. I changed the naming of ENV vars at some point, following the Next.js `PUBLIC_` naming for variables shared to the browser (which are therefore, made public).

Here is what your .env should look like, assuming you're using a version containing this commit https://github.com/UnlyEd/next-right-now/commit/df72481c54d28bbddf0ef3431a76e77899b53272:
https://github.com/UnlyEd/next-right-now/blob/v2-mst-aptd-at-lcz-sty/.env

First thing first, try things locally. If it doesn't work locally, it won't work online.

You can debug what happens at `amplitudeInstance.init` in https://github.com/UnlyEd/next-right-now/blob/df72481c54d28bbddf0ef3431a76e77899b53272/src/utils/analytics/amplitude.ts, make sure the API key is properly readable there.

The extension should show both $identity and actual events. Maybe you removed them? They're supposed to be generated by:
https://github.com/UnlyEd/next-right-now/blob/df72481c54/src/components/pageLayouts/DefaultLayout.tsx#L72

**Comment by sovattha** [comment]
Thanks for the effort @Vadorequest !

I know you cannot debug every single setup so I appreciate your commitment.

I forked the project at this commit: f4d9afa1600701a9cbe62fd8834fd9de99008df4 (13/04/2020) and did not update since then... Anyway the way the environment variables were used back in time (without the prefix PUBLIC) worked well.

The setup of Amplitude was also all correct.

You pointed my mistake: I somehow deleted the following snippet. I had no idea it was needed.

```<LogOnMount eventType="page-displayed" />```

It now works fine again.

**Comment by Vadorequest** [comment]
Glad you got it working! 👏

**Comment by Vadorequest** [comment]
@sovattha FYI https://unlyed.github.io/next-right-now/concepts/env-and-stages.html#public-environment-variables-vs-private-env-variables has been updated, alongside with doc regarding ENV vars configuration and usage.

**Comment by sovattha** [comment]
@Vadorequest Perfectly clear. Thanks for the info.

**Comment by MaxiSantos** [comment]
react-amplitude is not supported anymore. Use official amplitude ts https://github.com/amplitude/Amplitude-TypeScript/blob/main/examples/browser/next-app/pages/index.tsx

**Comment by Vadorequest** [comment]
Thanks for letting us know.

The current version of react-amplitude SDK works well and I'm not planning on migrating it soon, unless there are meaningful improvements or bugs/issues that it solves.
