### ISSUE TITLE
Unable to process command '::set-env name=CI::1' successfully

### ISSUE THREAD

**Issue by samuelcastro** [UnlyEd/next-right-now#207]
I'm having issue with cypress.

<img width="851" alt="Screen Shot 2020-11-20 at 1 57 53 PM" src="https://user-images.githubusercontent.com/5281701/99853779-74a40000-2b38-11eb-8ee0-3a0b3cd40f8b.png">

**Comment by samuelcastro** [comment]
https://github.com/UnlyEd/next-right-now/pull/208

**Comment by Vadorequest** [comment]
Thanks @samuelcastro, I noticed this a few days ago. I'm glad it's as simple as upgrading the version.

Would you have any idea how to trigger the workflow on https://github.com/UnlyEd/next-right-now/pull/208? It's one thing I really don't know how to improve and that makes contributions harder to test because CI/CD and tests aren't executed on PRs from contributors like you. (unlike what's done when a PR is open on the NRN repository)

**Comment by samuelcastro** [comment]
@Vadorequest This is possible using the `pull_request_target` event as described here: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull_request_target

**Comment by Vadorequest** [comment]
Yeah, but we moved away from pull_request event because there was many other issues with it, one of them is it won't trigger if there is any conflict, and other blocking things 😞

**Comment by samuelcastro** [comment]
Sorry I meant `pull_request_target` the `pull_request` event only happens during a merge.

**Comment by Vadorequest** [comment]
Fixed by https://github.com/UnlyEd/next-right-now/pull/209 which includes https://github.com/UnlyEd/next-right-now/pull/208

**Comment by Vadorequest** [comment]
Applied in all v2 branches.
