### ISSUE TITLE
List of Presets

### ISSUE THREAD

**Issue by samuelcastro** [UnlyEd/next-right-now#36]
Hi, I couldn't find a list of presets, is this documented somewhere?

Thanks!

**Comment by samuelcastro** [comment]
nvm, got it here: https://unlyed.github.io/next-right-now/getting-started/select-preset#common-to-all-presets

So right now there is only single preset right?

**Comment by samuelcastro** [comment]
Yeah it looks like it, closing.

**Comment by Vadorequest** [comment]
Yes, there is only one at the moment. I want to add more but need some time to do so.

What presets would you be looking for?

**Comment by samuelcastro** [comment]
So the `v1-ssr-mst-aptd-gcms-lcz-sty` is a great preset, I'm not sure I'd use GraphCMS though since Direct is for free, not completely sure yet.

**Comment by Vadorequest** [comment]
Any GraphQL-powered backend would work very similarly. (besides i18n content)

Directus is free, but you must host it somehow, so it's a bit more complex for a quick "getting started".
Of course you can use the Cloud version which comes with 1 month of free trial, but still gotta enter your payment information there, so that may be a blocker too.

There are other alternatives such as Strapi, but here comes again the question about how/where to host it.

**Comment by Vadorequest** [comment]
List of presets has been updated to make it easier to find.

https://unlyed.github.io/next-right-now/available-presets/
