### ISSUE TITLE
Locale subpaths

### ISSUE THREAD

**Issue by samuelcastro** [UnlyEd/next-right-now#38]
Hey @Vadorequest does this have support for locale subpaths? Like https://github.com/isaachinman/next-i18next#5-locale-subpaths.

Thanks!

**Comment by Vadorequest** [comment]
No, it doesn't because there was no need for it since it auto-detects the language and uses SSR.

But supporting i18n with SSG is gonna need locale subpaths, because everything will be statically generated.

So, it's possible to implement locale subpath with SSR, and it will eventually be supported with as SSG variant, but right now there is nothing available.

**Comment by samuelcastro** [comment]
Ok, just a small feedback, why just don't move `getInitialProps` from `_.app.tsx` to an HOC and use it in a page basis, this simple step would make free NRN to use SSG.

**Comment by Vadorequest** [comment]
That's an interesting way to solve this issue indeed. I'll give it a try, and it'll simplify the variants as well if I can use the same variant with both SSG/SSR per-page opt-in, it'd be much better. Thanks!

**Comment by Vadorequest** [comment]
@samuelcastro You should find this useful: https://github.com/zeit/next.js/discussions/10949#discussioncomment-6884

Also, I've started working on hybrid SSG/SSR at #42, but it's non-trivial and I'm still learning the Next.js internals related to the SSG feature.

**Comment by samuelcastro** [comment]
Sounds good, thanks!

**Comment by Vadorequest** [comment]
Locale subpath is now properly supported in #42, even though this branch isn't finished yet.

Closing this then.
