### ISSUE TITLE
Improvements to consider

### ISSUE THREAD

**Issue by samuelcastro** [UnlyEd/next-right-now#51]
I want to list a few things that can improve performance even more:

[Next Optimized Images](https://github.com/cyrilwanner/next-optimized-images): To optimize image load.
[Babel Import Graphql](https://www.npmjs.com/package/babel-plugin-import-graphql): Babel plugin to enable import syntax for `.graphql` and `.gql` files.
[Babel Plugin Graphql Tag](https://github.com/gajus/babel-plugin-graphql-tag): Reduces the script initialization time and removes the `graphql-tag` dependency

Thoughts?

**Comment by Vadorequest** [comment]
Thanks for the suggestion.

- [Next Optimized Images](https://github.com/cyrilwanner/next-optimized-images): To optimize image load.
  - Interesting, this could be great, especially with SSG, because all images could be optimised at build time.
- [Babel Import Graphql](https://www.npmjs.com/package/babel-plugin-import-graphql): Babel plugin to enable import syntax for `.graphql` and `.gql` files.
  - I don't see the interest, we already have a working way that isn't complicated and doesn't rely on external tooling.
- [Babel Plugin Graphql Tag](https://github.com/gajus/babel-plugin-graphql-tag): Reduces the script initialization time and removes the `graphql-tag` dependency
  - I can't tell if this provides any benefit, would you mind trying it out to see if the bundled size gets reduced when using it? Also, there is no usage example in the doc.

**Comment by Vadorequest** [comment]
Regarding 1), they're also working on a v3, and there are some drawbacks to using this lib (complex to configure, apparently)

https://github.com/cyrilwanner/next-optimized-images/issues/120

**Comment by samuelcastro** [comment]
I’m using all those libs in a project right now, I’d be glad to send a PR, setting up is fairly simple.

**Comment by Vadorequest** [comment]
Awesome. Could you make a pr for images optimisation and another for the babel plug-in graphql tag then? We'll see how much size improvement it'll do :)

**Comment by samuelcastro** [comment]
This is the image optimization PR: https://github.com/UnlyEd/next-right-now/pull/53

**Comment by samuelcastro** [comment]
This is the graphql-tag optimization PR: https://github.com/UnlyEd/next-right-now/pull/54

**Comment by Vadorequest** [comment]
I'm closing this in favour of the related PRs.
