### ISSUE TITLE
What is the purpose of using export and declare together?

### ISSUE THREAD

**Issue by crisfcodes** [UnlyEd/next-right-now#90]
https://github.com/UnlyEd/next-right-now/blob/0fd1aae03a283cf79e810467d07f3ec03a0f5508/src/types/pageProps/MultiversalPageProps.ts#L12

**Comment by Vadorequest** [comment]
https://stackoverflow.com/a/53289927/2391795

Honestly, I think it's a mistake on my side, and `export type MultiversalPageProps<E extends {} = {}> = {` should behave exactly the same.

The good thing is, it doesn't change anything in this case.

Eventually, I'll fix this by removing all `declare` statements related to TS `type`, good catch!

**Comment by Vadorequest** [comment]
Fixed by 

[https://github.com/UnlyEd/next-right-now/pull/86/commits/3e3a7526801c207d1a0eb7ff077f129a5d507780 ](https://github.com/UnlyEd/next-right-now/pull/86/commits/3e3a7526801c207d1a0eb7ff077f129a5d507780)

[https://github.com/UnlyEd/next-right-now/pull/86/commits/3e3a7526801c207d1a0eb7ff077f129a5d507780 ](https://github.com/UnlyEd/next-right-now/pull/86/commits/3e3a7526801c207d1a0eb7ff077f129a5d507780)
